app.base-url=http://localhost:8080
spring.application.name=tournaments-backend-practice
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/testdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:testuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:testpassword}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.security=trace
spring.jpa.properties.hibernate.generate_statistics = true
logging.level.org.hibernate.state = DEBUG
spring.main.log-startup-info=true