package com.example.tournaments_backend.exception;

public enum ClientErrorKey {
    TOKEN_EXPIRED,
    INVALID_TOKEN,
    MISSING_TOKEN,
    RESET_TOKEN_NOT_FOUND,
    CONFIRMATION_TOKEN_NOT_FOUND,
    USER_NOT_FOUND,
    GAME_NOT_FOUND,
    GAME_STAT_NOT_FOUND,
    TEAM_NOT_FOUND,
    LEAGUE_NOT_FOUND,
    USER_ALREADY_EXISTS,
    EMAIL_ALREADY_CONFIRMED,
    PASSWORD_ALREADY_RESET,
    INVALID_INPUT,
    PERMISSION_DENIED,
    GAME_INACTIVE
}