package com.example.tournaments_mcp.tools;

import java.util.Map;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.example.tournaments_mcp.backend.LeagueStatus;

import io.modelcontextprotocol.json.McpJsonMapper;
import io.modelcontextprotocol.server.McpStatelessServerFeatures.SyncToolSpecification;
import io.modelcontextprotocol.spec.McpSchema.Tool;
import io.modelcontextprotocol.spec.McpSchema.ToolAnnotations;

/**
 * What the model sees, and how a call reaches a method.
 *
 * <p>This is the file the Spring AI branch did not need. There, {@code @McpTool}
 * on a method supplied the name, the description and the hints, and the input
 * schema was generated by reflecting over the parameter types -- which is why
 * that branch's pom had to keep {@code -parameters}. Here both halves are
 * written out: a {@link Tool} declaring the contract, and a handler pulling the
 * arguments back out of the map the client sent.
 *
 * <p>The schemas below are not invented. They reproduce, field for field, what
 * Spring AI generated for these same three methods, so a client cannot tell the
 * two servers apart. Deliberately so: the point of this branch is to price the
 * plumbing, not to redesign the tools.
 *
 * <p>The cost is per tool and it is small but real -- roughly fifteen lines
 * each, of which the schema is most. What it buys back is that the contract is
 * legible in one place instead of being a consequence of a method signature,
 * and that renaming a Java parameter can no longer change what a client sees.
 */
@Configuration
public class ToolCatalog {

    /**
     * Applies to all three tools: they read, they change nothing, asking twice
     * is the same as asking once, and the data lives in a system beyond this
     * process.
     */
    private static final ToolAnnotations READ_ONLY = ToolAnnotations.builder()
            .readOnlyHint(true)
            .destructiveHint(false)
            .idempotentHint(true)
            .openWorldHint(true)
            .build();

    private final ToolResults results;
    private final McpJsonMapper jsonMapper;

    public ToolCatalog(ToolResults results, McpJsonMapper jsonMapper) {
        this.results = results;
        this.jsonMapper = jsonMapper;
    }

    @Bean
    public SyncToolSpecification listLeaguesTool(McpLeagueTools tools) {
        Tool tool = Tool.builder()
                .name("list_leagues")
                .title("list_leagues")
                .description("List tournament leagues, optionally filtered by status. "
                        + "Returns a summary of each league without its teams; "
                        + "call get_league for the full roster.")
                .inputSchema(jsonMapper, """
                        {
                          "$schema": "https://json-schema.org/draft/2020-12/schema",
                          "type": "object",
                          "properties": {
                            "status": {
                              "type": "string",
                              "enum": ["NOT_STARTED", "IN_PROGRESS", "ENDED"],
                              "description": "Optional filter: NOT_STARTED, IN_PROGRESS, or ENDED"
                            }
                          },
                          "required": []
                        }
                        """)
                .annotations(READ_ONLY)
                .build();

        return SyncToolSpecification.builder()
                .tool(tool)
                .callHandler((context, request) -> results.of(
                        () -> tools.listLeagues(context, status(request.arguments()))))
                .build();
    }

    @Bean
    public SyncToolSpecification getLeagueTool(McpLeagueTools tools) {
        Tool tool = Tool.builder()
                .name("get_league")
                .title("get_league")
                .description("Get one league by id, including its teams and their players.")
                .inputSchema(jsonMapper, """
                        {
                          "$schema": "https://json-schema.org/draft/2020-12/schema",
                          "type": "object",
                          "properties": {
                            "leagueId": {
                              "type": "integer",
                              "format": "int64",
                              "description": "The league id"
                            }
                          },
                          "required": ["leagueId"]
                        }
                        """)
                .annotations(READ_ONLY)
                .build();

        return SyncToolSpecification.builder()
                .tool(tool)
                .callHandler((context, request) -> results.of(
                        () -> tools.getLeague(context, leagueId(request.arguments()))))
                .build();
    }

    @Bean
    public SyncToolSpecification listMyTeamsTool(McpTeamTools tools) {
        Tool tool = Tool.builder()
                .name("list_my_teams")
                .title("list_my_teams")
                .description("List the teams the current user plays for, and the teams "
                        + "they have been invited to join.")
                .inputSchema(jsonMapper, """
                        {
                          "$schema": "https://json-schema.org/draft/2020-12/schema",
                          "type": "object",
                          "properties": {},
                          "required": []
                        }
                        """)
                .annotations(READ_ONLY)
                .build();

        return SyncToolSpecification.builder()
                .tool(tool)
                .callHandler((context, request) -> results.of(() -> tools.listMyTeams(context)))
                .build();
    }

    /**
     * The optional status filter, or null when the client sent none.
     *
     * <p>No defence against a value outside the enum: the server validates
     * arguments against the schema above before this runs, so an unknown status
     * has already come back as an error result naming the allowed values.
     */
    private static LeagueStatus status(Map<String, Object> arguments) {
        Object status = arguments.get("status");
        return (status == null) ? null : LeagueStatus.valueOf(status.toString());
    }

    /**
     * The league id, as a long.
     *
     * <p>JSON has one number type, so what arrives is whatever Jackson chose --
     * an Integer for small ids, a Long past two billion. {@link Number} covers
     * both. The schema has already rejected a string and a missing value.
     */
    private static Long leagueId(Map<String, Object> arguments) {
        return ((Number) arguments.get("leagueId")).longValue();
    }
}
