POST http://localhost:8080/api/v1/auth/reset-password HTTP/1.1
content-type: application/json

{
    "token": "910af7e3-e382-4f39-aeaf-77fa45154aed",
    "email": "jdoe@gmail.com",
    "newPassword": "djfkdaof1"
}