name: Java CI with Maven and Postgres

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 23 # Match this to your local version
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Run Tests
      run: ./mvnw clean test
      env:
        SPRING_PROFILES_ACTIVE: test